# Generated by Django 5.0.3 on 2024-05-14 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parqueadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tarifa_hora', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_vehiculo', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('parqueadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_servicioParqueo.parqueadero')),
            ],
        ),
    ]
