# Generated by Django 5.0.3 on 2024-05-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_servicioParqueo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parqueadero',
            name='tarifa_hora_currency',
            field=models.CharField(default='COP', max_length=3),
        ),
        migrations.AlterField(
            model_name='parqueadero',
            name='tarifa_hora',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
